{% set version = "2.1.0" %}

package:
  name: cookiecutter
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cookiecutter/cookiecutter-{{ version }}.tar.gz
  sha256: eca3133ebd0d138f226616c38dc456caafae7da45d6d33a3eeb83bf7f56f9c64

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cookiecutter = cookiecutter.__main__:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - binaryornot >=0.4.4
    - click >=7.0,<9
    - jinja2 >=2.7,<4.0.0
    - jinja2-time >=0.2.0
    - python >=3.7
    - python-slugify >=4.0.0
    - pyyaml >=5.3.1
    - requests >=2.23.0

test:
  requires:
    - freezegun
    - git
    - mercurial  # [not (win and py3k)]
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - python
  source_files:
    - tests
  commands:
    - pip check
    - cookiecutter --version
    - cookiecutter --help
    - pytest tests -vv --cov=cookiecutter --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=100

about:
  home: https://github.com/cookiecutter/cookiecutter
  license_family: BSD
  license_file: LICENSE
  license: BSD-3-Clause
  doc_url: https://cookiecutter.readthedocs.io
  doc_source_url: https://github.com/cookiecutter/cookiecutter/tree/master/docs
  summary: |-
    A command-line utility that creates projects from project templates, e.g.
    creating a Python package project from a Python package project template.

extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
