{% set version = "2.6.0" %}

package:
  name: cookiecutter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cookiecutter/cookiecutter-{{ version }}.tar.gz
  sha256: db21f8169ea4f4fdc2408d48ca44859349de2647fbe494a9d6c3edfc0542c21c

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - cookiecutter = cookiecutter.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - arrow
    - binaryornot >=0.4.4
    - click >=7.0,<9.0.0
    - jinja2 >=2.7,<4.0.0
    - python >={{ python_min }}
    - python-slugify >=4.0.0
    - pyyaml >=5.3.1
    - requests >=2.23.0
    - rich

test:
  source_files:
    - tests
  requires:
    - coverage
    - freezegun
    - git
    - m2-grep  # [win]
    - mercurial  # [not (win and py3k)]
    - pip
    - pytest
    - pytest-mock
    - python {{ python_min }}
  commands:
    - pip check
    - cookiecutter --version
    - cookiecutter --version | grep -iE "Cookiecutter {{ version.replace(".", "\\.") }}"
    - pip list
    - pip list | grep -iE "cookiecutter\s+{{ version.replace(".", "\\.") }}"
    - cookiecutter --help
    - coverage run --source cookiecutter --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=98

about:
  home: https://github.com/cookiecutter/cookiecutter
  license_family: BSD
  license_file: LICENSE
  license: BSD-3-Clause
  doc_url: https://cookiecutter.readthedocs.io
  doc_source_url: https://github.com/cookiecutter/cookiecutter/tree/main/docs
  summary: |-
    A command-line utility that creates projects from project templates, e.g.
    creating a Python package project from a Python package project template.

extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
