{% set version = "1.7.3" %}

package:
  name: cookiecutter
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cookiecutter/cookiecutter-{{ version }}.tar.gz
  sha256: 6b9a4d72882e243be077a7397d0f1f76fe66cf3df91f3115dbb5330e214fa457

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cookiecutter = cookiecutter.cli:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - binaryornot >=0.4.4
    - click >=7.0
    - jinja2 <3.0.0a0
    - jinja2-time >=0.2.0
    - markupsafe <2.0.0
    - poyo >=0.5.0
    - python >=3.6
    - python-slugify >=4.0.0
    - requests >=2.23.0
    - six >=1.10

test:
  requires:
    - freezegun
    - git
    - mercurial  # [not (win and py3k)]
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - python
  source_files:
    - tests
  commands:
    - python -m pip check
    - cookiecutter --version
    - cookiecutter --help
    - py.test --cov=cookiecutter

about:
  home: https://github.com/cookiecutter/cookiecutter
  license_family: BSD
  license_file: LICENSE
  license: BSD-3-Clause
  doc_url: https://cookiecutter.readthedocs.io
  doc_source_url: https://github.com/cookiecutter/cookiecutter/tree/master/docs
  summary: >
    A command-line utility that creates projects from cookiecutters (project templates), e.g. creating a Python package project from a Python package project template.

extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
