{% set version = "1.5.0" %}
{% set gh_org = "audreyr" %}
{% set gh_repo = "cookiecutter" %}


package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: 553d00dcbdb6eed252ff15b5622ed98b2a22ffa96fc1b49717b4fbea32378526

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cookiecutter = cookiecutter.cli:main
  skip: True  # [py36]

requirements:
  build:
    - python
    - setuptools
  run:
    - binaryornot >=0.2.0
    - click >=5.0
    - future >=0.15.2
    - jinja2 >=2.7
    - jinja2-time >=0.1.0
    - poyo >=0.1.0
    - python
    - whichcraft >=0.4.0

test:
  requires:
    - freezegun
    - git
    - pytest
    - pytest-catchlog
    - pytest-cov
    - pytest-mock ==1.1
    - python
    - mercurial  # [py2k]
  source_files:
    - tests
  commands:
    - cookiecutter --version
    - cookiecutter --help
    - py.test --cov=cookiecutter -k "not test_make_sure_path_exists and not pypackage_git"

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license_family: BSD
  license_file: LICENSE
  license: BSD-3-Clause
  summary: >
            A command-line utility that creates projects from cookiecutters
            (project templates). E.g. Python package projects, jQuery plugin
            projects.

extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
