{% set version = "2.2.3" %}

package:
  name: cookiecutter
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cookiecutter/cookiecutter-{{ version }}.tar.gz
  sha256: d56f18c0c01c09804450b501ac43e8f6104cfa7cdd93610359c68b1ba9fd84d2

build:
  noarch: python
  number: 0
  script:
    # TODO: remove after https://github.com/cookiecutter/cookiecutter/issues/1886 is _actually_ resolved
    - {{ PYTHON }} -c "p = __import__('pathlib').Path('cookiecutter/__init__.py'); p.write_text(p.read_text(encoding='utf-8').replace('2.1.2.dev0', '2.2.2'), encoding='utf-8')"
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cookiecutter = cookiecutter.__main__:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - arrow
    - binaryornot >=0.4.4
    - click >=7.0,<9.0.0
    - jinja2 >=2.7,<4.0.0
    - python >=3.7
    - python-slugify >=4.0.0
    - pyyaml >=5.3.1
    - requests >=2.23.0

test:
  requires:
    - freezegun
    - git
    - m2-grep  # [win]
    - mercurial  # [not (win and py3k)]
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - python
  source_files:
    - tests
  commands:
    - pip check
    - cookiecutter --version
    - cookiecutter --version | grep -iE "Cookiecutter {{ version.replace(".", "\\.") }}"
    - pip list
    - pip list | grep -iE "cookiecutter\s+{{ version.replace(".", "\\.") }}"
    - cookiecutter --help
    - pytest tests -vv --cov=cookiecutter --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=100

about:
  home: https://github.com/cookiecutter/cookiecutter
  license_family: BSD
  license_file: LICENSE
  license: BSD-3-Clause
  doc_url: https://cookiecutter.readthedocs.io
  doc_source_url: https://github.com/cookiecutter/cookiecutter/tree/master/docs
  summary: |-
    A command-line utility that creates projects from project templates, e.g.
    creating a Python package project from a Python package project template.

extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
